url: "https://arindia.github.io"
name: Arigato
region: India

permalink: pretty

twitter: "https://twitter.com/arigatoin"
facebook: "https://www.facebook.com/arigatoindia/"
snapchat: "#"
instagram: "https://www.instagram.com/arigato.in/"
medium:  "https://medium.com/@arigato"

collections:
  help:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "help" # previously `post` in Jekyll 2.2.
    values:
      layout: "help"
